package trackmap

import (
	"encoding/json"
	"os"
	"strings"
)

// TrackRef holds reference metadata for a known track. Used to guide
// segment detection toward the expected corner count, and to label the
// detected corners with their real turn numbers and names.
type TrackRef struct {
	// Corners is the expected number of corner segments (a chicane counts as 1).
	Corners int `json:"corners"`

	// CornerNames labels the detected corner segments in track order from the
	// S/F line, one entry per corner. It exists because detection merges some
	// complexes, so the Nth detected corner is often not iRacing's turn N —
	// at Road America the detected 8th corner is really the Kink, turn 11.
	//
	// Entries are free text, so the T-number can be kept alongside a name
	// ("T11 Kink") or used on its own ("T3"). An empty entry leaves that
	// corner's auto-generated label alone, which allows annotating a track a
	// few corners at a time instead of all at once.
	//
	// Lives here rather than in trackmap.json because that file is
	// regenerated by detection and hand edits to it are lost.
	CornerNames []string `json:"cornerNames,omitempty"`

	// Comment is a human-readable description of the corner list.
	Comment string `json:"comment,omitempty"`
}

// TrackRefFile is the top-level type for trackref.json: a map from
// iRacing TrackDisplayName to reference metadata.
type TrackRefFile map[string]*TrackRef

// LoadTrackRef reads trackref.json from the given path. Returns an empty map
// (not nil) if the file doesn't exist. Returns an error only on malformed JSON.
func LoadTrackRef(path string) (TrackRefFile, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return TrackRefFile{}, nil
		}
		return nil, err
	}
	var trf TrackRefFile
	if err := json.Unmarshal(data, &trf); err != nil {
		return nil, err
	}
	if trf == nil {
		trf = TrackRefFile{}
	}
	return trf, nil
}

// Corners returns the expected corner segment count for the given track, and
// whether a reference exists.
func (trf TrackRefFile) Corners(trackName string) (int, bool) {
	ref, ok := trf[trackName]
	if !ok || ref == nil {
		return 0, false
	}
	return ref.Corners, true
}

// CornerNames returns the hand-annotated corner labels for a track, or nil if
// none are configured.
func (trf TrackRefFile) CornerNames(trackName string) []string {
	ref, ok := trf[trackName]
	if !ok || ref == nil {
		return nil
	}
	return ref.CornerNames
}

// CountCorners returns how many of segs are corners or chicanes — the segments
// CornerNames applies to.
func CountCorners(segs []Segment) int {
	n := 0
	for i := range segs {
		if segs[i].Kind == KindCorner || segs[i].Kind == KindChicane {
			n++
		}
	}
	return n
}

// ApplyCornerNames renames the corner segments of segs in track order using
// names, and reports how many labels it applied.
//
// It is deliberately all-or-nothing on length: if names does not have exactly
// one entry per corner, nothing is renamed and ok is false. A short or stale
// list would otherwise shift every label after the mismatch, silently
// mislabelling corners — the precise failure this feature exists to fix.
// Empty entries are skipped, leaving that corner's generated label in place.
func ApplyCornerNames(segs []Segment, names []string) (applied int, ok bool) {
	if len(names) == 0 {
		return 0, false
	}
	if CountCorners(segs) != len(names) {
		return 0, false
	}

	i := 0
	for si := range segs {
		if segs[si].Kind != KindCorner && segs[si].Kind != KindChicane {
			continue
		}
		if n := strings.TrimSpace(names[i]); n != "" {
			segs[si].Name = n
			applied++
		}
		i++
	}
	return applied, true
}
